from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("6.15.2")

##### load config #####
configfile: "config/config.yaml"

##### load rules #####
include: "rules/common.smk"
include: "rules/prepare_bam_file.smk"

##### target rules #####
rule all:
    input:
        expand("results/callConsensus/{sample}_MarkedDuplicates.sorted.bam", sample = sample_names),
