# path to the sample sheet in tsv format (columns: sample, R1, R2)
samples: config/samples.tsv
# path to the folder containing the input fastq files
input_fastqs: /cluster/work/nexus/internal_projects/umiPanel_pipeline/tests/linda_dev/fastqs/ 

# Path to project specific reference and bed files
referenceBwa: "/cluster/work/nexus/nilsson/nilsson_dx-pipeline_2020/reference_data/reference/Homo_sapiens_assembly38.fasta"
reference: "/cluster/work/nexus/nilsson/nilsson_dx-pipeline_2020/reference_data/reference/Homo_sapiens_assembly38.fasta"
bed: "/cluster/work/nexus/balabanov_chip_2020/bed_files/VariantPlex_Myeloid_CHIP_14783-v1.0.extended_region.bed"

# Computing resources required for lsf
# ToDo: Define requirements more precicly
computingResources:
    mediumRequirements:
        mem: 4000
        time: 700
        threads: 8

# Definition of project specific tool params
tools:
    
    fgbio:
        FastqToBam:
            variousParams: "-r 8M13S+T +T -library=PCR"
        CallConsensusReads:
            variousParams: "--min-reads=2"
        FilterConsensusReads:
            variousParams: "--min-reads 2 2 2 --max-base-error-rate 0.1 --max-read-error-rate 0.025 --min-base-quality 2"

    bwa:
        variousParams: "-M"

    freebayes:
        variousParams: "--haplotype-length 0 --pooled-continuous --pooled-discrete  --min-alternate-fraction 0.005 --min-alternate-count 4"

    lofreq:
        variousParams: "--no-default-filter -a 1 --min-cov 4 --call-indels"

    snpEff:
        variousParams: "-nodownload"
        dataDir: "/cluster/work/nexus/utilities/databases/snpEff/v43/"
        genomeVersion: "hg38"

containers:
    fgbio: "/cluster/customapps/nexus/sharedutils/tmp/fgbio_1.5.1--hdfd78af_0"
    picard: "/cluster/customapps/nexus/sharedutils/tmp/picard-slim_2.26.11--hdfd78af_0"
    bwa: "/cluster/customapps/nexus/sharedutils/tmp/bwa_0.7.17--h7132678_9"
